name: Mod Suggestion
description: Suggest a new mod
labels: [Suggestion]
body:
  - type: markdown
    attributes:
      value: |
      
        ## Before suggesting a mod please:
        
        - Make sure it hasn't been suggested before.
        - Keep in mind that every new mod makes the modpack a little harder to run.
          
  - type: input
    id: link
    attributes:
      label: URL
      description: Link to the mod on Curseforge
      placeholder: https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why would you like the mod added?
    validations:
      required: false
